FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './experiments' # Testing files saving path

DATASET:
  SMPL_PATH: '/data2/lrh/smpl_model/smpl'
  SMPLH_PATH: '/data2/lrh/smpl_model/smplh'
  SMPLX_PATH: '/data2/lrh/smpl_model/smplx'
  AISTPP:
    ROOT: /data2/lrh/dataset/aist/data/origin/30fps/fullset
    MOTION: /data2/lrh/dataset/aist/data/origin/30fps/fullset/dances139_60fps
    MUSIC: /data2/lrh/dataset/aist/data/origin/30fps/fullset/musics35_30fps
    normalizer: /data2/lrh/project/dance/Lodge/lodge302/data/AIST_Normalizer.pth
  AISTPP_60FPS:
    MOTION: /data2/lrh/dataset/aist/data/origin/30fps/fullset/dances139_60fps
    MUSIC: /data2/lrh/dataset/aist/data/origin/60fps/fullset/musics35_60fps
  FINEDANCE:
    ROOT: /data/lrh/datasets/fine_dance/origin
  FINEDANCE_139CUT:
    ROOT: /data2/lrh/dataset/fine_dance/gound
    MOTION: /data2/lrh/dataset/fine_dance/gound/mofea319
    MUSIC: /data2/lrh/dataset/fine_dance/gound/musicfea_edge
    normalizer: /data2/lrh/project/dance/Lodge/lodge302/data/Normalizer.pth
  FINEDANCE_263CUT:
    ROOT: /data2/lrh/dataset/fine_dance/mofea263cut
    MOTION: /data2/lrh/dataset/fine_dance/mofea263cut/new_joint_vecs
    MUSIC: /data2/lrh/dataset/fine_dance/mofea263cut/musicfea_edge
    normalizer:
      target: dld.data.utils.preprocess.Normal
      params:
        mean: /data2/lrh/dataset/fine_dance/mofea263cut/normfile/Mean.npy  #/data2/lrh/dataset/fine_dance/mofea263cut/Mean.npy
        std: /data2/lrh/dataset/fine_dance/mofea263cut/normfile/Std.npy
  DOUBLEDANCE_263:
    TXTINFO: /data2/lrh/dataset/fine_dance/total/mofea266/finedance_pair_exists.txt
    ROOT: /data2/lrh/dataset/fine_dance/total/mofea266/mofea263
    MOTION: /data2/lrh/dataset/fine_dance/total/mofea266/mofea263/new_joint_vecs
    MUSIC: /data2/lrh/dataset/fine_dance/origin/music_feature35_edge
    RELATIVE_DIS: /data2/lrh/dataset/fine_dance/total/mofea266/relative_dis.pkl
    normalizer:
      target: dld.data.utils.preprocess.Normal
      params:
        mean: /data2/lrh/dataset/fine_dance/total/mofea266/mofea263/Mean.npy
        std: /data2/lrh/dataset/fine_dance/total/mofea266/mofea263/Std.npy
  DOUBLEDANCE_266:
    TXTINFO: /data2/lrh/dataset/fine_dance/total/mofea266/finedance_pair_exists.txt
    ROOT: /data2/lrh/dataset/fine_dance/total/mofea266/
    MOTION: /data2/lrh/dataset/fine_dance/total/mofea266/new_joint_vecs
    MUSIC: /data2/lrh/dataset/fine_dance/origin/music_feature35_edge
    RELATIVE_DIS: /data2/lrh/dataset/fine_dance/total/mofea266/relative_dis.pkl
    normalizer:
      target: dld.data.utils.preprocess.Normal
      params:
        mean: /data2/lrh/dataset/fine_dance/total/mofea266/Mean.npy
        std: /data2/lrh/dataset/fine_dance/total/mofea266/Std.npy

